### PR TITLE
expose ProxyServer

### PR DESCRIPTION
**Pull request by legokichi**
https://github.com/chimurai/http-proxy-middleware/issues/189

### CODE REVIEW

**Comment by chimurai** [comment]
Thanks for the PR @legokichi 

Are the any reasons to expose the whole proxy server instead of just the `close` function?

**Comment by legokichi** [comment]
@chimurai In addition to calling methods of the ProxyServer class, we can also call methods of [http/https](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/index.js#L127) class. It becomes easy to hack. But adding middleware.close is sufficient for my use.

**Comment by judikdavid** [comment]
Exposing a proxy server would be good to handle POST requests as well, like shown here:
https://github.com/nodejitsu/node-http-proxy/issues/1142#issuecomment-282810543
Without that, the middleware cannot proxy POST API requests.

**Comment by chimurai** [comment]
`proxyReq` is exposed via the `onProxyReq` config:

https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onproxyreq

**Comment by judikdavid** [comment]
@chimurai Thank you, did not noticed that option 💯

**Comment by chimurai** [comment]
fixed in #508

proxy closes automatically with a graceful server shutdown

**Pull request closed without merging**
