### PR TITLE
Hook into http-proxy onProxyReq

### PR DESCRIPTION
**Pull request by trbngr**
I need to be able to setHeader

### CODE REVIEW

**Comment by trbngr** [comment]
Also opens up logging the proxied request. ;)

**Comment by chimurai** [comment]
Thanks for the PR.

You should already be able to set the request headers with `option.headers`.
Apart from that; I think it's useful to expose http-proxy's proxyReq event.

Could you document the `onProxyReq` option in the README and provide a tiny example of its usage?

The code coverage dropped significantly. I think it's caused by `describe.only` in: https://github.com/chimurai/http-proxy-middleware/pull/28/files#diff-47a0c4f7ac32f4602b09040919af54f2R427

Lastly, could you squash you commits to keep the commits clean?

**Comment by chimurai** [comment]
got the chance to update the pull request so it can be merged?

**Comment by trbngr** [comment]
I got so busy that I forgot about it. I'll do it today. ;)

**Comment by chimurai** [comment]
Great! Looking forward to it :)

**Comment by chimurai** [comment]
Any luck to update this PR?

I was hoping to include this on the next release. Otherwise I'll postpone this PR to a later release.

Mean concerns are the dropped code coverage and the documentation of the new option.

**Comment by trbngr** [comment]
My apologies. Life has had me busy and I totally spaced it.

I can get on it right now.

**Comment by trbngr** [comment]
and there she is! :+1:

**Comment by trbngr** [comment]
dang it

**Comment by trbngr** [comment]
I should've used a feature branch. Sorry for this.

**Comment by trbngr** [comment]
finally. So sorry.

**Comment by trbngr** [comment]
crap. haha.

**Comment by trbngr** [comment]
Dude. I've made a mess. I went one commit too far. It includes your notes.

**Comment by trbngr** [comment]
If this is a no-go, you can delete this PR and I'll create a new one.

**Comment by chimurai** [comment]
A new PR would be nice, if it isn't too much effort.

**Comment by chimurai** [comment]
Closing PR.
Functionality is implemented in #32

**Pull request closed without merging**
