### PR TITLE
 return 504, 502 and 500 as appropriate Fixes #131 

### LINKED ISSUE #131: http-proxy-middleware should return 500, 504 and 502 as appropriate.
### Expected behavior
If there's an error in the upstream server response return 502,
If there's a timeout in the upstream response / DNS / TLS handshake etc return 504
If there's an application error / unexpected exception in http-proxy-middleware return 500

### Actual behavior
Any error returns 500

### Setup

* http-proxy-middleware: latest / N/A

#### proxy middleware configuration
N/A

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Nice, looks good.

**Comment by graingert** [comment]
@SpaceK33z not a breaking change over HTTP. The HTTP spec is very clear that servers can return these error codes, and clients should support them.  Any client that does a hardcoded detection of '500' is not HTTP compliant, and should expect to be broken.

**Comment by graingert** [comment]
@chimurai woop it's green now

**Comment by chimurai** [comment]
Thanks for the PR @graingert.

Definitely a better usage of the http status codes. Don't mind if this PR breaks existing hardcoded detection because of this improvement.

This `defaultErrorHandler` is overridable  with the [`onError`](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onerror) option if you want a customized error handling.

So if someone still wants to rely on the hardcoded `500` http error, they can use the `onError` option to achieve that.

----
Some background info why this default error handler exists.

From the `http-proxy` documentation:
> **proxy events**
> `error`: The error event is emitted if the request to the target fail. **We do not do any error handling of messages passed between client and proxy, and messages passed between proxy and target, so it is recommended that you listen on errors and handle them.**

**Comment by chimurai** [comment]
published in `v0.17.3`

hope this doesn't cause much regression :)

**Comment by SpaceK33z** [comment]
Awesome @chimurai :).

**Pull request merged**
