### PR TITLE
feat: async pathRewrite

### PR DESCRIPTION
**Pull request by rsethc**
Related issue: https://github.com/chimurai/http-proxy-middleware/issues/374

### CODE REVIEW

**Comment by chimurai** [comment]
Nice. Looks good.

The following needs to be in place before this PR can be accepted:

- Updated documentation README.md
- unit test(s) for pathRewriter 
- unit test types.spec.ts (testing for the async syntax)

You can have a look at:
Similar PR, but async router: https://github.com/chimurai/http-proxy-middleware/pull/379/files

Unit tests for path rewriter:
https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/path-rewriter.spec.ts

Types test:
https://github.com/chimurai/http-proxy-middleware/blob/master/test/types.spec.ts
example of async router: https://github.com/chimurai/http-proxy-middleware/blob/master/test/types.spec.ts#L74

**Comment by rsethc** [comment]
Alright, I'll take a look at solving these requirements. Thanks

**Comment by rsethc** [comment]
I think this is ready to have another look. One change I made by accident affected the `yarn.lock` file, let me know if it's preferable to add a commit that undoes that.

**Comment by chimurai** [comment]
Yes, please undo the changes to `yarn.lock`

I'll checkout the PR to do some additional testing.

**Comment by chimurai** [comment]
Thanks!

Published a new beta version

You can install it with:
`npm install http-proxy-middleware@beta` or `npm install http-proxy-middleware@0.21.0-beta.3`

Let me know if everything still works. I'll publish a final shortly after confirmation.

**Comment by rsethc** [comment]
Thanks, I'll try out this version and let you know if anything goes wrong.

**Comment by rsethc** [comment]
The "http-proxy-middleware@0.21.0-beta.3" seems to work as expected in what I'm working on.

**Comment by chimurai** [comment]
published final version: `http-proxy-middleware@0.21.0`

**Pull request merged**
