### PR TITLE
changed res.end to specify a callback so the error message will be wr…

### PR DESCRIPTION
**Pull request by mTazelaar**
…itten once the response stream is finished.

### CODE REVIEW

**Comment by chimurai** [comment]
Hmmm... Build is failing for Node v0.10

Could you explain use case for this PR?

**Comment by mTazelaar** [comment]
I was getting some '[HPM] Proxy error: ECONNRESET' errors from jetty that was causing the proxy to stop working. not sure why the fix is failing on the 0.10 build. I did try using the fix with option.onError and it does solve the problem for me. thanks

**Comment by chimurai** [comment]
0.10 has an older api, which expects a String in the first argument.

I'll consider dropping support for node 0.10 for the v1.x release.
Think this fix will be a good addition for v1.x if more users experience the same issue.

Thanks for this PR. Might be useful if other users encounter the same error.

**Comment by mTazelaar** [comment]
sounds good. thanks

**Pull request closed without merging**
