### PR TITLE
Preventing the fail of the 'ETIMEDOUT' code in 500 'Internal server error'

### PR DESCRIPTION
**Pull request by aremishevsky**
Currently `ETIMEDOUT` code is handled by the `defaultErrorHandler` as a `[500] Internal Server Error`. 
It should be handled as the regular `ECONNRESET` || `ENOTFOUND` || `ECONNREFUSED` || `ETIMEDOUT` codes.

### CODE REVIEW

**Comment by aremishevsky** [comment]
@chimurai could you please review this PR?

**Comment by aremishevsky** [comment]
Can someone review and merge this PR?

**Comment by chimurai** [comment]
Can you add `ETIMEDOUT` to this unit test with the `504` response?

https://github.com/chimurai/http-proxy-middleware/blob/master/test/unit/handlers.spec.ts#L101

**Comment by aremishevsky** [comment]
@chimurai I did that https://github.com/chimurai/http-proxy-middleware/pull/480/files#diff-5dce20e137b0cf4ccabefadbb48baf14ef3c1d68b2dad6aa2b45d4bfbfbdf2e3R107

**Comment by chimurai** [comment]
Oops, missed that. 🙈

**Comment by chimurai** [comment]
Thanks for this PR!

**Comment by aremishevsky** [comment]
Could you please let me know when the new version would be available on the npm?

**Comment by chimurai** [comment]
Published in [v1.1.0](https://github.com/chimurai/http-proxy-middleware/releases/tag/v1.1.0)

**Pull request merged**
