### PR TITLE
Looks like travis is broken

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@chimurai there's something wrong with your end to end tests

**Comment by chimurai** [comment]
Thanks for noticing.

I re-ran an old job, which is failing now.
https://travis-ci.org/chimurai/http-proxy-middleware/jobs/172738003

Have to investigate what causing this failure...

**Comment by chimurai** [comment]
Seems to be related to github service outage...

> github:status
> « Dashboard
> Status Messages
> December 06, 2016
> 
> 21:54 W. Europe Standard Time Everything operating normally.
> 21:50 W. Europe Standard Time Service has returned and we are continuing to monitor the situation.
> 21:08 W. Europe Standard Time Major service outage.

https://status.github.com/messages
https://www.traviscistatus.com/

**Comment by graingert** [comment]
Nice can you rerun my other pr?

**Pull request closed without merging**
