### PR TITLE
refactor: avoid using lodash where possible

### PR DESCRIPTION
**Pull request by TrySound**
Using lodash methods does not add value where native methods and
operators can be used. In this diff I avoided lodash where possible.

Also fixed a few async tests (returned promise).

### CODE REVIEW

**Comment by TrySound** [comment]
Friendly ping @chimurai

**Comment by chimurai** [comment]
Hi @TrySound 

Thanks for the PR. 
Some effort was already started in this thread. https://github.com/chimurai/http-proxy-middleware/issues/428

Noticed some `skipped` tests. What is the reason for that?

**Comment by TrySound** [comment]
I wish I remember. Probably they were not stable locally even before my changes.

**Comment by TrySound** [comment]
I plan to continue the effort after merging this PR.

**Comment by TrySound** [comment]
Retry DeepCode

**Comment by TrySound** [comment]
Hi @@chimurai is this good to go?

**Comment by chimurai** [comment]
Hi @TrySound,

Thanks for the reminder.

Got a question:
A return statement was added in the unit tests; i.e. `return expect(rewriter(rewriteFn)).resolves.toBe('/123/456');`

Doesn't look like it's needed for this PR. Was there a reason for this?

**Comment by TrySound** [comment]
Some tests errored with unhandled rejection when I debugged code. Promise should be returned there. Nothing need to return explicitly with async await btw.

**Comment by TrySound** [comment]
Friendly ping @chimurai

**Comment by gwellner** [comment]
Friendly ping from 2021, is this still in work ?

**Comment by chimurai** [comment]
Thanks!

**Pull request merged**
