### PR TITLE
chore(deps): http-proxy 1.18.1

### PR DESCRIPTION
**Pull request by chimurai**
fixes: https://github.com/chimurai/http-proxy-middleware/issues/439

https://www.npmjs.com/advisories/1486

### CODE REVIEW

**Comment by vtereshyn** [comment]
Please, merge this PR. We're waiting for resolving audit issue in several repositories!

**Comment by chimurai** [comment]
published in `http-proxy-middleware@1.0.4`

**Comment by lvenkatraman** [comment]
I tried upgrading to 1.0.4 and I got  TypeError: proxy is not a function
wherever I used imports..
 const proxy = require('http-proxy-middleware');

**Comment by lvenkatraman** [comment]
do I need to have a dependency on http-proxy for this to work?

**Comment by chimurai** [comment]
Good to always check the changelog for breaking changes when you upgrade to a new **major** version.

You'll see that the import/require changed:

https://github.com/chimurai/http-proxy-middleware/releases/tag/v1.0.0

**Comment by lvenkatraman** [comment]
thanks!

**Pull request merged**
