### PR TITLE
feat(router): Add ability for router function to resolve to a proxyTable

### PR DESCRIPTION
**Pull request by stramel**
Just thought it would be cool to resolve to a dynamic proxyTable. Unit Tests are added to cover the changes. Please let me know if something else should be changed.

### CODE REVIEW

**Comment by chimurai** [comment]
Hi @stramel,

Thanks for the PR.
Could you explain how a dynamic proxyTable would be beneficial?

**Comment by stramel** [comment]
@chimurai So my thought is based on my use case and also partially, I thought it was odd not to support it. Anyways:

I have the following environments:

- `d-<tenant>.localhost:9000`
- `d-future-<tenant>.localhost:9000`
- `q-<tenant>.localhost:9000`
- `q-future-<tenant>.localhost:9000`
- `i-<tenant>.localhost:9000`
- ...
- `<tenant>.localhost:9000`

All of which routes under `/rest/` are getting routed to an API like so: `<env (optional)>-<tenant>.domain.com`. those are straight forward. 

However, I also have an environment where I want to point to my local API. So ideally, I would assign some other arbitrary "env" to it like `local-` or `l-` and route it to `localhost:8000`. 

Most of my configuration like this is abstracted into environment configuration file(s) so it would be nice to have all the proxies in a table while being able to dynamically create the routing targets for part of the configuration.

Perhaps I am over complicating it as well. I am open to suggestions.

**Comment by chimurai** [comment]
Hi @stramel,

Thanks for explaining your use-case.

The idea of providing a function as `router`, is to allow the developer to customise the routing behaviour to fit the needs of more complex use-cases. When a simple route table is not sufficient enough.

In your use-case it would be better to resolve your `proxyTable` to a `target` **within** the `router` function; e.g. The `router` function should return the new `target`.

From the library point of view I would like to keep the interface simple and it should fit a broad range of use-cases.

**Comment by stramel** [comment]
@chimurai I just wanted to check if you would like this to be part of the interface or not. If not you can close it out. Thanks!

**Comment by chimurai** [comment]
Hi @stramel 

Really appreciate your PR.

But from library point of view I would like to keep the interface simple and fit a broad range of use-cases.

Hope you can still fulfil your use-case with the existing api.

I'll close the PR.

**Pull request closed without merging**
