### PR TITLE
Conditionally write to the console when proxy events occur

### PR DESCRIPTION
**Pull request by adeneui**
Added an option for printing the logging statements since they are filling up my production logs and test runs.

Please take a look when you get a chance @chimurai

### CODE REVIEW

**Comment by chimurai** [comment]
Thanks for the pull request @adeneui 

I was actually working on this issue on the `logger` branch.
Had a feeling the console.log statements would start to itch someone sooner or later :)

What I had in mind was actually a more flexible setup.
I created two issues to share my thoughts.

#26: Allows you to control the logging levels. You'll be able to disable logging, but it will also allow you to log everything. This might be handy for debugging purposes.

#27: Allows you to set your own log provider, such as winston or log4js. This should greatly enhance the logging abilities. (Write log statements to file or database, etc...)

I hope the proposed setup will fit the needs of many.
Let me know what you think and feel free to comment.

**Comment by adeneui** [comment]
Sounds good to me.  Do you have an idea of which one you would prefer (since they seem somewhat orthogonal)?  I can refactor this PR to accommodate #26 without much hassle.

**Comment by chimurai** [comment]
I prefer the `logger` branch. It will implement #26 and #27.
The included tests should prevent regression in the logging functionality.

It's almost ready to be merged back.

**Comment by mpareja** [comment]
+1
We throw JSON logs at ElasticSearch and it gets upset when the input isn't in the JSON format it's expecting.

**Comment by chimurai** [comment]
Closing PR.
Functionality is implemented in #30

**Pull request closed without merging**
